# Generated by Django 5.0.1 on 2024-03-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-status',)},
        ),
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('mexio', 'Mexico'), ('United_states', 'united_states'), ('Canada', 'canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Paused', 'paused'), ('Bought', 'bought')], max_length=10),
        ),
    ]
