# Generated by Django 5.0.1 on 2024-03-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_options_sale_address_alter_sale_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('Mexico', 'mexio'), ('United_states', 'united_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('paused', 'Paused'), ('bought', 'Bought')], max_length=10),
        ),
    ]
