# Generated by Django 5.0.1 on 2024-03-24 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_country_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='takedOffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('Mexico', 'mexico'), ('United_states', 'united_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Paused', 'paused'), ('Bought', 'bought')], max_length=10),
        ),
    ]
