# Generated by Django 5.0.1 on 2024-03-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_slug_sale_takedoffer_alter_sale_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('mexico', 'Mexico'), ('United_states', 'united_states'), ('Canada', 'canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Paused', 'paused'), ('Pending', 'pending'), ('bought', 'Bought')], default='pending', max_length=10),
        ),
    ]
