# Generated by Django 5.0.1 on 2024-03-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_country_alter_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='takedOffer',
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('Mexico', 'mexico'), ('united_states', 'United_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('paused', 'Paused'), ('Pending', 'pending'), ('taked_offer', 'Taked_offer'), ('Bought', 'bought')], default='pending', max_length=11),
        ),
    ]
