# Generated by Django 5.0.1 on 2024-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_created_at_alter_sale_status_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('Mexico', 'mexico'), ('united_states', 'United_states'), ('Canada', 'canada')], max_length=15),
        ),
    ]
