# Generated by Django 5.0.1 on 2024-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_sale_country_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('mexico', 'Mexico'), ('united_states', 'United_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Paused', 'paused'), ('pending', 'Pending'), ('taked_offer', 'Taked_offer'), ('reported', 'Reported'), ('bought', 'Bought')], default='pending', max_length=11),
        ),
    ]
