# Generated by Django 5.0.1 on 2024-03-25 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_sale_country_alter_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('Mexico', 'mexico'), ('United_states', 'united_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Paused', 'paused'), ('pending', 'Pending'), ('taked_offer', 'Taked_offer'), ('Reported', 'reported'), ('Bought', 'bought')], default='pending', max_length=11),
        ),
    ]
