# Generated by Django 5.0.1 on 2024-03-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sale_buyer_alter_sale_country_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('mexico', 'Mexico'), ('United_states', 'united_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cryptoAmmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('paused', 'Paused'), ('Pending', 'pending'), ('Taked_offer', 'taked_offer'), ('reported', 'Reported'), ('bought', 'Bought')], default='pending', max_length=11),
        ),
    ]
