# Generated by Django 5.0.1 on 2024-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_sale_address_alter_sale_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cryptoAmmount',
        ),
        migrations.AddField(
            model_name='sale',
            name='rangeAmmount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('Mexico', 'mexico'), ('united_states', 'United_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Paused', 'paused'), ('pending', 'Pending'), ('Taked_offer', 'taked_offer'), ('reported', 'Reported'), ('Bought', 'bought')], default='pending', max_length=11),
        ),
    ]
