# Generated by Django 5.0.1 on 2024-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_sale_country_alter_sale_rangeammount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.CharField(choices=[('mexico', 'Mexico'), ('united_states', 'United_states'), ('canada', 'Canada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Paused', 'paused'), ('Pending', 'pending'), ('Taked_offer', 'taked_offer'), ('reported', 'Reported'), ('Bought', 'bought')], default='Pending', max_length=11),
        ),
    ]
