# Generated by Django 5.0.1 on 2024-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
