# Generated by Django 5.0.1 on 2024-05-26 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_sale_buyed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='rangeAmmount',
        ),
        migrations.AlterField(
            model_name='comments',
            name='sale_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
