# Generated by Django 5.0.1 on 2024-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_sale_country_remove_sale_rangeammount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('pending', 'Pending'), ('looking', 'Looking'), ('taked_offer', 'Taked offer'), ('reported', 'Reported'), ('bought', 'Bought')], default='pending', max_length=11),
        ),
    ]
