# Generated by Django 5.0.1 on 2024-06-01 03:27

import apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to=apps.sales.models.public_thumbnail_directory),
        ),
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
