# Generated by Django 5.0.1 on 2024-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_sale_address_alter_sale_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bitcoin_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
