# Generated by Django 5.0.1 on 2024-03-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user_basic', 'User_basic'), ('Owner', 'owner'), ('moderator', 'Moderator')], default='user_basic', max_length=25),
        ),
    ]
