# Generated by Django 5.0.1 on 2024-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('User_basic', 'user_basic'), ('Owner', 'owner'), ('Moderator', 'moderator')], default='user_basic', max_length=25),
        ),
    ]
