# Generated by Django 5.0.1 on 2024-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user_basic', 'User_basic'), ('owner', 'Owner'), ('Moderator', 'moderator')], default='user_basic', max_length=25),
        ),
    ]
