# Generated by Django 5.0.1 on 2024-06-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('User_basic', 'user_basic'), ('owner', 'Owner'), ('moderator', 'Moderator')], default='user_basic', max_length=25),
        ),
    ]
