# Generated by Django 5.0.1 on 2024-03-31 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_sale_status'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTXO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used')], default='active', max_length=6)),
                ('ammount', models.FloatField(default=0)),
                ('slug', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sale_slug', to='sales.sale')),
            ],
        ),
    ]
