# Generated by Django 5.0.1 on 2024-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_utxo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utxo',
            name='ammount',
        ),
        migrations.AddField(
            model_name='utxo',
            name='address',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
