# Generated by Django 5.0.1 on 2024-05-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_utxo_ammount_utxo_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='ammountInCrypto',
            new_name='amountInCrypto',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='coin',
        ),
        migrations.AddField(
            model_name='utxo',
            name='wallet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='utxos', to='wallet.wallet'),
            preserve_default=False,
        ),
    ]
