# Generated by Django 5.0.1 on 2024-06-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_ammountincrypto_wallet_amountincrypto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utxo',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
